export const LABELS = {
  all: '全部',
  instant: '即時',
  preorder: '預購',
  mine: '我的',
  myHosted: '我開的',
  myJoined: '我加入的',
  login: '登入',
  account: '帳號',
  logout: '登出',
  memberInfo: '會員資料',
  membershipCard: 'Costco 會員卡',
  displayName: '顯示名稱',
  loginWithLine: 'LINE 登入',
  loginPromptTitle: '登入後即可管理個人資料與發起團購',
  loginPromptBody: '將會透過 LINE OAuth popup 完成登入，成功後會取得 JWT Token。',
  close: '關閉',
  currentStore: '門市',
  searchPlaceholder: '搜尋商品名稱、關鍵字或類別',
  createDeal: '發起團購',
  remaining: '剩餘數量',
  itemUnit: '件',
  unitPrice: '單價',
  leader: '主揪',
  meetupPlace: '面交地點',
  meetupTime: '面交時間',
  storeName: '店面名稱',
  categoryName: '類別',
  creditScore: '信用分數',
  noMoreDeals: '目前沒有更多團購單',
  loadingMore: '載入中...',
  noMoreData: '沒有更多資料',
  latestMessages: '最新通知',
  loadState: '載入狀態',
  save: '儲存',
  saving: '儲存中...',
  theme: '主題模式',
  guestState: '尚未登入',
  referenceLoading: '正在載入店面與類別資料...',
  emptyDeals: '目前沒有符合條件的團購單',
  noValue: '未提供',
  notificationsTitle: '通知',
  notificationsBody: '目前尚未串接通知 API，這裡先保留給後續功能使用。',
  createCampaignTitle: '建立新的團購單',
  createCampaignSuccess: '團購單已送出',
  store: '店面',
  category: '類別',
  scenarioType: '團購類型',
  itemName: '商品名稱',
  itemImages: '商品圖片',
  pendingQuantity: '待認購數量',
  expireTime: '截止時間',
  meetupDateTime: '面交時間',
  meetupLocationLabel: '面交地點',
  selectStore: '請選擇店面',
  selectCategory: '請選擇類別',
  saveCampaign: '儲存團購單',
  savingCampaign: '儲存中...',
  loginRequiredForMine: '請先登入後查看「我的」團購',
};

export const TYPE_OPTIONS = [
  { value: 'INSTANT', label: LABELS.instant },
  { value: 'SCHEDULED', label: LABELS.preorder },
];

export const MY_CAMPAIGN_OPTIONS = [
  { value: 'ALL', label: '全部' },
  { value: 'HOSTED', label: '我的團購' },
  { value: 'JOINED', label: '我參加的' },
  { value: 'COMPLETED', label: '已完成' },
  { value: 'CANCELLED', label: '已取消' },
];

export const EXPIRE_PRESET_OPTIONS = [
  { value: '10m', label: '10 分鐘', minutes: 10 },
  { value: '20m', label: '20 分鐘', minutes: 20 },
  { value: '30m', label: '30 分鐘', minutes: 30 },
  { value: 'custom', label: '自訂', minutes: null },
];

export const PAGE_SIZE = 10;
