export const LABELS = {
  all: '全部',
  instant: '即時',
  preorder: '預購',
  login: '登入',
  account: '帳號',
  logout: '登出',
  memberInfo: '個人資料',
  membershipCard: '好市多會員卡',
  displayName: '顯示名稱',
  loginWithLine: 'LINE 登入',
  loginPromptTitle: '登入後即可開始發起與參與團購',
  loginPromptBody: '此頁會透過 LINE OAuth popup 完成登入，成功後自動帶回 JWT Token。',
  close: '關閉',
  currentStore: '目前店面',
  searchPlaceholder: '搜尋商品名稱、店面或類別',
  createDeal: '發起團購',
  remaining: '剩餘數量',
  itemUnit: '份',
  unitPrice: '單價',
  leader: '團主',
  meetupPlace: '面交地點',
  meetupTime: '面交時間',
  storeName: '店面位置',
  categoryName: '類別',
  creditScore: '信用分',
  noMoreDeals: '目前沒有更多團購單',
  loadingMore: '載入中...',
  noMoreData: '沒有更多資料',
  latestMessages: '最新通知',
  loadState: '載入狀態',
  save: '儲存',
  saving: '儲存中...',
  theme: '主題模式',
  guestState: '尚未登入',
  referenceLoading: '門市與類別資料載入中...',
  emptyDeals: '目前沒有符合條件的團購單',
  noValue: '未提供',
  notificationsTitle: '通知',
  notificationsBody: '目前尚未串接通知 API，這裡先保留通知入口。',
  createCampaignTitle: '建立新的團購單',
  createCampaignSuccess: '團購單已送出',
  store: '店面',
  category: '類別',
  scenarioType: '團購類型',
  itemName: '商品名稱',
  itemImages: '商品圖片',
  pendingQuantity: '待認購數量',
  expireTime: '截止時間',
  meetupDateTime: '面交時間',
  meetupLocationLabel: '面交地點',
  selectStore: '請選擇店面',
  selectCategory: '請選擇類別',
  saveCampaign: '送出團購單',
  savingCampaign: '送出中...',
};

export const TYPE_OPTIONS = [
  { value: 'INSTANT', label: LABELS.instant },
  { value: 'SCHEDULED', label: LABELS.preorder },
];

export const EXPIRE_PRESET_OPTIONS = [
  { value: '10m', label: '10分鐘後', minutes: 10 },
  { value: '20m', label: '20分鐘後', minutes: 20 },
  { value: '30m', label: '30分鐘後', minutes: 30 },
  { value: 'custom', label: '自訂', minutes: null },
];

export const PAGE_SIZE = 10;
